# Generated by Django 3.0 on 2020-10-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('animal welfare', 'Animal Welfare'), ('arts & culture', 'Arts & Culture'), ('children', 'Children'), ('development', 'Development'), ('disability', 'Disability'), ('education', 'Education'), ('elderly', 'Elderly'), ('environment', 'Environment'), ('governance', 'Governance'), ('health', 'Health'), ('women', 'Women'), ('livelihood', 'Livelihood')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('mp', 'mp'), ('up', 'mp'), ('rj', 'rj'), ('cg', 'cg')], max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('ngo_logo', models.ImageField(upload_to='pics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoreg.Ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('daddress', models.TextField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoreg.Ngo')),
            ],
        ),
    ]
